services:
  pysimulator:
    image: kkzhang3/taiji-pysim:v1.0.0
    working_dir: /PySimulator
    command: ["python", "main.py"]
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

# docker-compose -f docker-compose.pysimulator.yml up -d